var CCV;
var proto;

if (!CCV)
	CCV = {};

if (!CCV.global)
	CCV.global = {};

CCV.global.RED = 0xFF3E29;
CCV.global.BLUE = 0xADD2EA;

CCV.global.PRELOAD_AUDIO_DELTA = 3;
CCV.global.PRELOAD_LAYER_DELTA = 7;
CCV.global.PRELOAD_SEQUENCE_DELTA = 2;
CCV.global.SCENE_ACTIVATE_BORDING_SCENES = true;

CCV.global.HEADER_HEIGHT = 0;
CCV.global.FOOTER_HEIGHT = 0;

CCV.global.SYS_FORCE_CANVAS = true;
CCV.global.SYS_USE_SHARED_TICKER = true;
CCV.global.SYS_FPS = 8;
CCV.global.SYS_ALLOW_LARGE = false;
CCV.global.SYS_AUTO_ACTIVATION = false;
CCV.global.SYS_WIN_FOCUS_ACTIVATION = false;
CCV.global.SYS_WORKSHOP_MODE = false;

CCV.global.DEBUG_LANDSCAPE_GFX = false;
CCV.global.DEBUG_SCENE_DELTA = false;
CCV.global.DEBUG_SCENE_GFX = false;
CCV.global.DEBUG_SCENE_MARGINS = false;

CCV.global.AUDIO_ENABLED = true;
CCV.global.AUDIO_FOLDER = 'ccv/audio/';
CCV.global.AUDIO_GLOBAL_VOLUME = .01;
/* fade in duration in seconds */
CCV.global.AUDIO_FADEIN_LENGTH = 2;
/* fade out duration in seconds */
CCV.global.AUDIO_FADEOUT_LENGTH = 2;

CCV.global.SCENE_START_INDEX = 32;
CCV.global.SCENE_START_RAND = false;
CCV.global.SCENE_ACTIVATION_DELAY = 500;
CCV.global.SCENE_DEACTIVATION_DELAY = 1400;
CCV.global.SCENE_REPEAT_DELAY = 4000;
CCV.global.SCENE_RESTART_DELAY = 2000;
CCV.global.SCENE_SLIDE_DURATION = 1.6;
CCV.global.SCENE_MAX_HEIGHT = 650;
CCV.global.SCENE_EXTRAVIEW_COEF = .25;
CCV.global.SCENE_GROUND_HEIGHT = 100;

CCV.global.SCENE_ITEM_BEFORE = 15;

CCV.global.MEDIA_FOLDER = 'ccv/';

CCV.global.MAGNIFIER_RED = 0xFF1515;
CCV.global.MAGNIFIER_PINCH_AMP = 200;
CCV.global.MAGNIFIER_PINCH_INCREMENT = .5;
CCV.global.MAGNIFIER_APPEAR_TIME = .7;
CCV.global.MAGNIFIER_VANISH_TIME = .5;
CCV.global.MAGNIFIER_RADIUS = 150;
CCV.global.MAGNIFIER_DRAG_IDLE_TEMPO = -1;
CCV.global.MAGNIFIER_DRAG_REFRESH_INDEX = 500;
CCV.global.MAGNIFIER_DRAG_SCROLL_LIMIT = 160;
CCV.global.MAGNIFIER_DRAG_SCROLL_INC = 5;

CCV.global.SCROLL_ELASTICITY = .06;